# Generated by Django 4.2.7 on 2023-11-16 03:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Elo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Fila",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Modalidade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Servico",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("purchase_date", models.DateField(default=datetime.datetime.now)),
                ("purchase_time", models.TimeField(default=datetime.datetime.now)),
                ("deadline", models.DateField()),
                ("completed", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "elo_final",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="servicos_finais", to="core.elo"
                    ),
                ),
                (
                    "elo_inicial",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="servicos_iniciais", to="core.elo"
                    ),
                ),
                ("fila", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="core.fila")),
                (
                    "modalidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="servicos", to="core.modalidade"
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
