# Generated by Django 4.2.7 on 2023-12-08 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "status",
            },
        ),
        migrations.RemoveField(
            model_name="servico",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="deadline",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="elo_final",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="elo_inicial",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="fila",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="modalidade",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="purchase_date",
        ),
        migrations.RemoveField(
            model_name="servico",
            name="purchase_time",
        ),
        migrations.AddField(
            model_name="servico",
            name="current_elo",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="servicos_iniciais", to="core.elo"
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="payment_method",
            field=models.CharField(default="pix", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="queue",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="refer_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="riot_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="riot_login",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="riot_password",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="riot_tag",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="service",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="target_elo",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="servicos_finais",
                to="core.elo",
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="time",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="servico",
            name="status",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="servicos_status", to="core.status"
            ),
        ),
    ]
