# Generated by Django 4.2.7 on 2023-11-16 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="status",
            options={"verbose_name_plural": "status"},
        ),
        migrations.RemoveField(
            model_name="servico",
            name="completed",
        ),
        migrations.AddField(
            model_name="servico",
            name="status",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="servicos_status", to="core.status"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="elo_final",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="servicos_finais", to="core.elo"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="elo_inicial",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="servicos_iniciais", to="core.elo"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="fila",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.fila"),
        ),
        migrations.AlterField(
            model_name="servico",
            name="modalidade",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="servicos", to="core.modalidade"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
