# Generated by Django 4.2.7 on 2023-11-16 04:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_status_options_remove_servico_completed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="modalidade",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="servicos", to="core.modalidade"
            ),
        ),
        migrations.AlterField(
            model_name="servico",
            name="purchase_date",
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="purchase_time",
            field=models.TimeField(default=datetime.datetime.now, null=True),
        ),
    ]
