# Generated by Django 4.2.7 on 2023-12-08 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_servico_current_elo_alter_servico_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="time",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="servico",
            name="user",
            field=models.ForeignKey(
                default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
