# Generated by Django 4.2.7 on 2023-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_servico_time_alter_servico_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="purchase_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
