# Generated by Django 4.2.7 on 2023-12-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_servico_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servico",
            name="purchase_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
