# Generated by Django 4.2.7 on 2023-12-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_servico_purchase_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="servico",
            name="current_elo_image",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="servico",
            name="target_elo_image",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
